name: tf-checks
permissions:
  id-token: write
  contents: read
on:
  pull_request:
    paths:
      - '**/*.tf'
      - '*.tf'
jobs:
  single-account-example:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: './examples/single_account/'
      provider: aws
      enable_plan: true
      show_plan: false
    secrets:
      BUILD_ROLE: ${{ secrets.BUILD_ROLE }}
  main-account-example:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: './examples/multi_account/main_account/'
      provider: aws
      enable_plan: true
      show_plan: false
    secrets:
      BUILD_ROLE: ${{ secrets.BUILD_ROLE }}
  slave-account-example:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: './examples/multi_account/slave_account/'
      provider: aws
      enable_plan: true
      show_plan: false
    secrets:
      BUILD_ROLE: ${{ secrets.BUILD_ROLE }}
